# Site Settings
title: Seong-Yong Park
description: Personal Portfolio & Blog
author: Seong-Yong Park
email: park50260@gmail.com
url: https://Seong-Yong-Park.github.io
baseurl: ""

# Build Settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Windows file watching
force_polling: true

# Theme Settings
theme: null

# Navigation
navigation:
  - title: Resume
    url: /
  - title: Blog
    url: /blog

# Language Settings
lang: ko
languages: ["ko", "en"]
default_lang: ko

# Contact Information
contact:
  location: "성남, 대한민국"
  email: park50260@gmail.com
  phone: "+82-10-2661-5026"
  linkedin: "www.linkedin.com/in/성용-박-88769a329"
  github: Seong-Yong-Park
  # twitter: your-twitter
  # website: https://yourwebsite.com

# Social Links (optional)
social:
  github: Seong-Yong-Park
  linkedin: "www.linkedin.com/in/성용-박-88769a329"
  # twitter: your-twitter

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

